name: Environment Variables Example

on: [push] #метод запуска

env:
  NODE_ENV: production
  TEST_ENV: ${{ vars.DOCKER_USERNAME }}
  TEST_SECRET: ${{ secrets.DOCKER_TOKEN }}

jobs:
  build: #название джобы
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Display environment variables
        run: |
          echo NODE_ENV is $NODE_ENV
          echo TEST_ENV is $TEST_ENV
          echo TEST_SECRET is $TEST_SECRET

