name: File Change Based Workflow in Monorepo

on:
  push:
    branches:
      - develop
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build frontend
        run: |
          echo "Building frontend..."
          cd frontend
          # Add build commands for frontend here


  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy frontend
        run: |
          echo "Deploying frontend..."
          cd frontend
          # Add deployment commands for frontend here

